new version for single PSQL instances
Proemion/repmgr-agent pull request #5
Opened 2018-05-03 08:44 UTC by mfuhrmann

2018-05-11 12:56 UTC, mfuhrmann commented
@Svedrin Can you please merge this one?

2018-05-29 10:01 UTC, Svedrin requested changes
@mfuhrmann one nit, apart from that lgtm.

2018-05-29 10:01 UTC, Svedrin commented on v2/pgdeploy
> +        print remote_host["ip_addr"]
@mfuhrmann let's get rid of this print :)

2018-05-30 11:10 UTC, mfuhrmann commented
@Svedrin *ping*

2018-05-30 12:02 UTC, Svedrin approved these changes

2018-05-30 12:02 UTC, merged